const DATA_ESCOM = {
    escuela: "Escuela Superior de Cómputo (ESCOM)",
    carreras: {
        isc: {
            nombre: "Ingeniería en Sistemas Computacionales",
            planes: {
                2009: {
                    color_class: "isc-2009",
                    semestres: {
                        1: [
                            {
                                nombre: "CÁLCULO",
                                clave: "CAL",
                                info: {
                                    fecha: "2026-06-10",
                                    horario: "10:00 - 12:00",
                                    coordinador: "Dr. Jurado",
                                    correo: "perez@escom.ipn.mx",
                                    salon: "A-203",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante_url: "docs/guias/isc2009/calculo.pdf",
                                    nota: "Llevar calculadora científica",
                                },
                            },
                            {
                                nombre: "Matematicas Discretas",
                                clave: "MD",
                                info: {
                                    fecha: "2026-06-10",
                                    horario: "10:00 - 12:00",
                                    coordinador: "Dr. Erik Valentin",
                                    correo: "...",
                                    salon: "...",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante: "docs/guias/isc2009/calculo.pdf",
                                    nota: "...",
                                },
                            },
                            {
                                nombre: "Funadmentos de Programacion",
                                clave: "FundPro",
                                info: {
                                    fecha: "2026-06-10",
                                    horario: "10:00 - 12:00",
                                    coordinador: "...",
                                    correo: "...",
                                    salon: "...",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante: "docs/guias/isc2009/calculo.pdf",
                                    nota: "...",
                                },
                            },
                            {
                                nombre: "Analisis Vectorial",
                                clave: "AV",
                                info: {
                                    fecha: "2026-06-10",
                                    horario: "10:00 - 12:00",
                                    coordinador: "Dr. Ortuño",
                                    correo: "...",
                                    salon: "...",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante: "docs/guias/isc2009/calculo.pdf",
                                    nota: "...",
                                },
                            },
                            {
                                nombre: "Comunicacion Oral y Escrita",
                                clave: "COE",
                                info: {
                                    fecha: "...",
                                    horario: "...",
                                    coordinador: "...",
                                    correo: "...",
                                    salon: "...",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante: "docs/guias/isc2009/calculo.pdf",
                                    nota: "...",
                                },
                            },
                        ],
                        2: [
                            {
                                nombre: "Algoritmos y Estructuras de Datos",
                                clave: "AED",
                                info: {
                                    fecha: "2026-06-10",
                                    horario: "10:00 - 12:00",
                                    coordinador: "Portillo",
                                    correo: "perez@escom.ipn.mx",
                                    salon: "A-203",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante_url: "docs/guias/isc2009/calculo.pdf",
                                    nota: "Llevar calculadora científica",
                                },
                            },
                            {
                                nombre: "Algebra Lineal",
                                clave: "ALA",
                                info: {
                                    fecha: "2026-06-10",
                                    horario: "10:00 - 12:00",
                                    coordinador: "Dr. Lule",
                                    correo: "...",
                                    salon: "...",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante: "docs/guias/isc2009/calculo.pdf",
                                    nota: "...",
                                },
                            },
                            {
                                nombre: "Calculo Aplicado",
                                clave: "CALA",
                                info: {
                                    fecha: "2026-06-10",
                                    horario: "10:00 - 12:00",
                                    coordinador: "Dr. Ortuño",
                                    correo: "...",
                                    salon: "...",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante: "docs/guias/isc2009/calculo.pdf",
                                    nota: "...",
                                },
                            },
                        ],
                    },
                },
                2020: {
                    color_class: "isc-2020",
                    semestres: {
                        1: [
                            {
                                nombre: "CÁLCULO",
                                clave: "CAL",
                                info: {
                                    fecha: "2026-06-10",
                                    horario: "10:00 - 12:00",
                                    coordinador: "Dr. Jurado",
                                    correo: "perez@escom.ipn.mx",
                                    salon: "A-203",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante_url: "docs/guias/isc2009/calculo.pdf",
                                    nota: "Llevar calculadora científica",
                                },
                            },
                            {
                                nombre: "Matematicas Discretas",
                                clave: "MD",
                                info: {
                                    fecha: "2026-06-10",
                                    horario: "10:00 - 12:00",
                                    coordinador: "Dr. Erik Valentin",
                                    correo: "...",
                                    salon: "...",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante: "docs/guias/isc2009/calculo.pdf",
                                    nota: "...",
                                },
                            },
                            {
                                nombre: "Analisis Vectorial",
                                clave: "AV",
                                info: {
                                    fecha: "2026-06-10",
                                    horario: "10:00 - 12:00",
                                    coordinador: "Dr. Ortuño",
                                    correo: "...",
                                    salon: "...",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante: "docs/guias/isc2009/calculo.pdf",
                                    nota: "...",
                                },
                            },
                            {
                                nombre: "Fundamentos de Programacion",
                                clave: "FP",
                                info: {
                                    fecha: "...",
                                    horario: "...",
                                    coordinador: "...",
                                    correo: "...",
                                    salon: "...",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante: "docs/guias/isc2009/calculo.pdf",
                                    nota: "...",
                                },
                            },
                            {
                                nombre: "Comunicacion Oral y Escrita",
                                clave: "COE",
                                info: {
                                    fecha: "...",
                                    horario: "...",
                                    coordinador: "...",
                                    correo: "...",
                                    salon: "...",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante: "docs/guias/isc2009/calculo.pdf",
                                    nota: "...",
                                },
                            },
                        ],
                        2: [
                            {
                                nombre: "Algoritmos y Estructuras de Datos",
                                clave: "AED",
                                info: {
                                    fecha: "2026-06-10",
                                    horario: "10:00 - 12:00",
                                    coordinador: "Portillo",
                                    correo: "perez@escom.ipn.mx",
                                    salon: "A-203",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante_url: "docs/guias/isc2009/calculo.pdf",
                                    nota: "Llevar calculadora científica",
                                },
                            },
                            {
                                nombre: "Algebra Lineal",
                                clave: "ALA",
                                info: {
                                    fecha: "2026-06-10",
                                    horario: "10:00 - 12:00",
                                    coordinador: "Dr. Lule",
                                    correo: "...",
                                    salon: "...",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante: "docs/guias/isc2009/calculo.pdf",
                                    nota: "...",
                                },
                            },
                            {
                                nombre: "Calculo Aplicado",
                                clave: "CALA",
                                info: {
                                    fecha: "2026-06-10",
                                    horario: "10:00 - 12:00",
                                    coordinador: "Dr. Levario",
                                    correo: "...",
                                    salon: "...",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante: "docs/guias/isc2009/calculo.pdf",
                                    nota: "...",
                                },
                            },
                            {
                                nombre: "Comunicacion Oral y Escrita",
                                clave: "COE",
                                info: {
                                    fecha: "...",
                                    horario: "...",
                                    coordinador: "...",
                                    correo: "...",
                                    salon: "...",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante: "docs/guias/isc2009/calculo.pdf",
                                    nota: "...",
                                },
                            },
                        ],
                    },
                },
            },
        },
        ia: {
            nombre: "Ingeniería en Inteligencia Artificial",
            planes: {
                2020: {
                    color_class: "ia-color",
                    semestres: {
                        1: [
                            {
                                nombre: "CÁLCULO",
                                clave: "CAL",
                                info: {
                                    fecha: "2026-06-10",
                                    horario: "10:00 - 12:00",
                                    coordinador: "Dr. Jurado",
                                    correo: "perez@escom.ipn.mx",
                                    salon: "A-203",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante_url: "docs/guias/isc2009/calculo.pdf",
                                    nota: "Llevar calculadora científica",
                                },
                            },
                            {
                                nombre: "Matematicas Discretas",
                                clave: "MD",
                                info: {
                                    fecha: "2026-06-10",
                                    horario: "10:00 - 12:00",
                                    coordinador: "Dr. Erik Valentin",
                                    correo: "...",
                                    salon: "...",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante: "docs/guias/isc2009/calculo.pdf",
                                    nota: "...",
                                },
                            },
                            {
                                nombre: "Funadmentos de Programacion",
                                clave: "FundPro",
                                info: {
                                    fecha: "2026-06-10",
                                    horario: "10:00 - 12:00",
                                    coordinador: "...",
                                    correo: "...",
                                    salon: "...",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante: "docs/guias/isc2009/calculo.pdf",
                                    nota: "...",
                                },
                            },
                            {
                                nombre: "Mecanica y Electromagnetismo",
                                clave: "MecElectro",
                                info: {
                                    fecha: "...",
                                    horario: "...",
                                    coordinador: "...",
                                    correo: "...",
                                    salon: "...",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante: "docs/guias/isc2009/calculo.pdf",
                                    nota: "...",
                                },
                            },
                            {
                                nombre: "Comunicacion Oral y Escrita",
                                clave: "COE",
                                info: {
                                    fecha: "...",
                                    horario: "...",
                                    coordinador: "...",
                                    correo: "...",
                                    salon: "...",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante: "docs/guias/isc2009/calculo.pdf",
                                    nota: "...",
                                },
                            },
                            {
                                nombre: "Fundamentos Economicos",
                                clave: "FE",
                                info: {
                                    fecha: "...",
                                    horario: "...",
                                    coordinador: "...",
                                    correo: "...",
                                    salon: "...",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante: "docs/guias/isc2009/calculo.pdf",
                                    nota: "...",
                                },
                            },
                        ],
                    },
                },
            },
        },
        lcd: {
            nombre: "Licenciatura en Ciencia de Datos",
            planes: {
                2020: {
                    color_class: "lcd-color",
                    semestres: {
                        1: [
                            {
                                nombre: "CÁLCULO",
                                clave: "CAL",
                                info: {
                                    fecha: "2026-06-10",
                                    horario: "10:00 - 12:00",
                                    coordinador: "Dr. Jurado",
                                    correo: "perez@escom.ipn.mx",
                                    salon: "A-203",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante_url: "docs/guias/isc2009/calculo.pdf",
                                    nota: "Llevar calculadora científica",
                                },
                            },
                            {
                                nombre: "Matematicas Discretas",
                                clave: "MD",
                                info: {
                                    fecha: "2026-06-10",
                                    horario: "10:00 - 12:00",
                                    coordinador: "Dr. Erik Valentin",
                                    correo: "...",
                                    salon: "...",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante: "docs/guias/isc2009/calculo.pdf",
                                    nota: "...",
                                },
                            },
                            {
                                nombre: "Funadmentos de Programacion",
                                clave: "FundPro",
                                info: {
                                    fecha: "2026-06-10",
                                    horario: "10:00 - 12:00",
                                    coordinador: "...",
                                    correo: "...",
                                    salon: "...",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante: "docs/guias/isc2009/calculo.pdf",
                                    nota: "...",
                                },
                            },
                            {
                                nombre: "Comunicacion Oral y Escrita",
                                clave: "COE",
                                info: {
                                    fecha: "...",
                                    horario: "...",
                                    coordinador: "...",
                                    correo: "...",
                                    salon: "...",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante: "docs/guias/isc2009/calculo.pdf",
                                    nota: "...",
                                },
                            },
                        ],
                    },
                },
            },
        },
        isisa: {
            nombre: "Ingeniería en Sistemas Automotrices",
            planes: {
                2020: {
                    color_class: "isisa-color",
                    semestres: {
                        1: [
                            {
                                nombre: "CÁLCULO Diferencial e Integral",
                                clave: "CAL",
                                info: {
                                    fecha: "2026-06-10",
                                    horario: "10:00 - 12:00",
                                    coordinador: "Dr. Jurado",
                                    correo: "perez@escom.ipn.mx",
                                    salon: "A-203",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante_url: "docs/guias/isc2009/calculo.pdf",
                                    nota: "Llevar calculadora científica",
                                },
                            },
                            {
                                nombre: "Fisica",
                                clave: "Fisica",
                                info: {
                                    fecha: "2026-06-10",
                                    horario: "10:00 - 12:00",
                                    coordinador: "Dr. Erik Valentin",
                                    correo: "...",
                                    salon: "...",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante: "docs/guias/isc2009/calculo.pdf",
                                    nota: "...",
                                },
                            },
                            {
                                nombre: "Fundamentos de Algebra",
                                clave: "FA",
                                info: {
                                    fecha: "2026-06-10",
                                    horario: "10:00 - 12:00",
                                    coordinador: "Dr. Erik Valentin",
                                    correo: "...",
                                    salon: "...",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante: "docs/guias/isc2009/calculo.pdf",
                                    nota: "...",
                                },
                            },
                            {
                                nombre: "Fundamentos de Programacion",
                                clave: "FP",
                                info: {
                                    fecha: "...",
                                    horario: "...",
                                    coordinador: "...",
                                    correo: "...",
                                    salon: "...",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante: "docs/guias/isc2009/calculo.pdf",
                                    nota: "...",
                                },
                            },
                            {
                                nombre: "Humanidades ",
                                clave: "Humanidades",
                                info: {
                                    fecha: "...",
                                    horario: "...",
                                    coordinador: "...",
                                    correo: "...",
                                    salon: "...",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante: "docs/guias/isc2009/calculo.pdf",
                                    nota: "...",
                                },
                            },
                            {
                                nombre: "Quimica Basica",
                                clave: "QB",
                                info: {
                                    fecha: "...",
                                    horario: "...",
                                    coordinador: "...",
                                    correo: "...",
                                    salon: "...",
                                    proyecto: "N/A",
                                    guia_url: "docs/guias/isc2009/calculo.pdf",
                                    comprobante: "docs/guias/isc2009/calculo.pdf",
                                    nota: "...",
                                },
                            },
                        ],
                    },
                },
            },
        },
    },
};
